[target.thumbv7em-none-eabihf]
# runner = "arm-none-eabi-gdb -q -x openocd.gdb"
runner = "gdb-multiarch -q -x openocd"

rustflags = [
  "-C", "link-arg=-Tmemory.x",
]

[build]
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)

[profile.release]
debug = 1 # default is `false`; using `true` is also OK as symbols reside on the host, not the target